import type { Metadata } from "next";
import "../src/styles/globals.css";
import Layout from "@/components/Layout/Layout";
import { vazir } from "../public/FONT/Vazir";


export const metadata: Metadata = {
  title: "Tommy Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className={vazir.variable} dir="rtl">
      <body className="bg-black font-[var(--font-vazir)]">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
